services:
  api:
    depends_on:
      db:
        condition: service_healthy
    image: oven/bun:1.2.20
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun start:api"
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
    networks:
      - financial-network

  app:
    image: oven/bun:1.2.20
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun start:app"
    ports:
      - '8080:5173'
    volumes:
      - ./:/usr/src/app
    networks:
      - financial-network

  db:
    image: mysql:9.3.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
    ports:
      - 3306:3306
    volumes:
      - financial-db:/var/lib/mysql
    networks:
      - financial-network

volumes:
  financial-db:

networks:
  financial-network:
    driver: bridge
